page_addfriend/urls.py
from django.conf.urls import url
from .views import index, new_friend

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^new_friend', new_friend, name = 'new_friend'),
    ]

page_dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

page_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

page_updatestatus/urls.py
from django.conf.urls import url
from .views import index
from .views import update_activity,clear,update_comment

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'update_activity/$', update_activity, name='update_activity'),
    url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear'),
    url(r'^update_comment/(?P<pk>[0-9]+)', view=update_comment, name='update_comment'),
 ]

tp01/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import page_profile.urls as page_profile
import page_updatestatus.urls as page_updatestatus
import page_addfriend.urls as page_addfriend
import page_dashboard.urls as page_dashboard
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile-page/', include(page_profile,namespace='profile-page')),
    url(r'^status/', include(page_updatestatus,namespace='status')),
    url(r'^add-friend/', include(page_addfriend, namespace='add-friend')),
    url(r'^dashboard/', include(page_dashboard, namespace='dashboard')),
    url(r'^$', RedirectView.as_view(url='status/', permanent=True), name='index'),
]

page_addfriend/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Friend(models.Model):
    def convert_timezone():
        return timezone.now() + timezone.timedelta(hours=7)
       
    name = models.CharField(max_length=30)
    url = models.URLField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)
    time = models.DateTimeField(default=convert_timezone)

page_dashboard/models.py
from django.db import models

# Create your models here.

page_profile/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
	name = models.CharField(max_length=27)
	gender = models.CharField(max_length=6)
	description = models.TextField(max_length=300)
	email = models.EmailField()

class Expertise(models.Model):
	expertise = models.TextField(max_length=100)

page_updatestatus/models.py
from django.db import models

class Update(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    activity = models.TextField()

class Comment(models.Model):
    comment = models.TextField()
    update = models.ForeignKey(Update, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

page_addfriend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'All inputs are required'
    }

    name_attrs = {
        'type': 'text',
        'class' : 'form-control',
        'placeholder': 'Name'
    }

    url_attrs = {
        'type': 'url',
        'class' : 'form-control',
        'placeholder' : 'http://test.com'
    }

    name = forms.CharField(label='Name ', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL ', required=True, max_length=200, widget=forms.URLInput(attrs=url_attrs))

page_updatestatus/forms.py
from django import forms

class Update_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs = {
        'type': 'text',
        'cols': 60,
        'rows': 10,
        'class': 'update-form-textarea',
        'placeholder':' Whats on your mind. . . '
    }

    activity = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs ={
        'type': 'text',
        'cols': 60,
        'rows': 10,
        'class': 'comment-form-textarea',
        'placeholder':' Write your comment here. . '
    }
    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

page_addfriend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

response={}
# Create your views here.
def index(request):
    friend = Friend.objects.all()
    response['friend'] = friend
    html = 'page_addfriend/page_addfriend.html'
    response['friend_form'] = Friend_Form
    return render(request, html, response)

def new_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=response['name'], url=response['url'])
        friend.save()
        return HttpResponseRedirect('/add-friend/')
    else:
        return HttpResponseRedirect('/add-friend/')

page_dashboard/views.py
from django.shortcuts import render
from page_updatestatus.models import Update
from page_addfriend.models import Friend
from page_profile.views import user_name
# Create your views here.

response = {}
def index(request):
    response['countFriend'] = Friend.objects.count()
    response['countUpdate'] = Update.objects.count()
    response['lastUpdate'] = Update.objects.last()
    response['name'] = user_name
    return render(request, 'page_dashboard.html', response)

page_profile/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Profile, Expertise
# Create your views here.


user_name = 'Kelompok 9 PPW-C' #TODO Implement this, put your name here
birth_date = date(2017,10,13)
birthdate = birth_date.strftime('%d %B') #TODO Implement this, format (Year, Month, Date)
gender = 'Female' #TODO Implement this, put your gender here
descript = 'PPW is fun'
email = 'kelompok9@ppwc.com'


expertise_dict = ['UI/UX','Designer', 'Happy', 'Coding']


def index(request):
	profile = Profile(name=user_name,gender=gender, description=descript, email=email)
	expertise = Expertise(expertise=expertise_dict)
	response = {'Name': profile.name,'Birthday': birthdate,'Gender':profile.gender, 'Description':profile.description, 'Email': profile.email, 'Expert' : expertise.expertise}
	html = 'page_profile.html'
	return render(request, html, response)

page_updatestatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Update, Comment
from .forms import Update_Form, Comment_Form


response = {}
user_name = 'Kelompok 9 PPW-C'
def index(request):
    response['user_name'] = user_name
    updates = Update.objects.all().order_by('-date')
    comments = Comment.objects.all().order_by('-date')
    response['updates'] = updates
    response['comments'] = comments
    response['update_form'] = Update_Form
    response['comment_form'] = Comment_Form
    return render(request, 'page_updatestatus.html', response)

def update_activity(request):
    form = Update_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['activity'] = request.POST['activity']
        updates = Update(activity=response['activity'])
        updates.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def update_comment(request,pk):
    update = Update.objects.get(pk=pk)
    form = Comment_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['comment'] = request.POST['comment']
        comments = Comment(comment=response['comment'])
        comments.update = update
        comments.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def clear(request,object_id):
    clears = Update.objects.get(pk=object_id)
    clears.delete()
    return HttpResponseRedirect('/status/')

page_addfriend/templates/page_addfriend/page_addfriend.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/page_addfriend.css' %}" />
<h1 class="main-title">ADD FRIEND</h1>
<hr/>
<section name="input-form" id="input-form">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add-friend:new_friend' %}">
            <h2 class="form-title">Add New Friend</h2>
            {% csrf_token %}
            {{ friend_form }}
            <button type="submit" class="btn btn-warning">Add Friend</button>
            <br>
        </form>
    </div>
</section>
<section name="friend-list" id="friend-list">
    <div class="container">      
        <div class="flex">
        <h2 class="friend-list-title">Friend List</h2>
        {% for data in friend %}
            <div class="flex-item">
                <div class="friend-box">
                    <div class="friend-img">
                        <img class="img" src="https://78.media.tumblr.com/3490e178451a95a930d793195d9b3747/tumblr_o54730zBMZ1qeu5jko2_500.gif" alt="PICT">
                    </div>    
                    <div class="friend-name">
                        {{data.name}}
                    </div>
                    <div class="friend-url">
                        <a href={{data.url}} target="_blank">{{data.url}}</a>
                    </div>
                    <div class="friend-added">
                        Added {{data.created_date}}
                    </div>
                </div>
            </div>
        {% endfor %}    
        </div>
    </div>
</section>

{% endblock %}

page_dashboard/templates/page_dashboard.html
{% extends "base.html"%}
{%block content%}
{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/page_dashboard.css' %}"/>
<h1 align="center" class="textcolor"> Statistic </h1>
 
<h2 align="center" class="textcolor"> <img class="img-circle" src="https://78.media.tumblr.com/3490e178451a95a930d793195d9b3747/tumblr_o54730zBMZ1qeu5jko2_500.gif") alt="My Photo" style=width:128px;height:128px> {{name}}</h2> 
</img> 
<hr/>

<p align="center" class="textcolor2"> Friends: {{countFriend}} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Feed: {{countUpdate}}</p>
<hr/>

<p align='center' class="textcolor5"> Latest Post </p>
<p align='center' class="textcolor"> <img src="https://78.media.tumblr.com/3490e178451a95a930d793195d9b3747/tumblr_o54730zBMZ1qeu5jko2_500.gif") alt="My Photo 2" style=width:50px;height:50px> {{name}}</p> </img>
<p align='center' class="textcolor3">{{lastUpdate.activity}}</p>
<p align='center' class="textcolor4">{{lastUpdate.date}}</p>
<hr/>
{%endblock%}

page_profile/templates/page_profile.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/page_profile.css' %}"/>
<h2>PROFILE</h2>
    <section name="card">
    	<div class="card">
        	<div class="top-section"></div>
                <img class="img" src="https://78.media.tumblr.com/3490e178451a95a930d793195d9b3747/tumblr_o54730zBMZ1qeu5jko2_500.gif" alt="PICT"> 
            <div class="bottom-section"></div>
                <h4>{{Name}}</h4>
            		<ul>
    	        		<table>
    		                <tr>
    		                    <td>Birthday</td>
    		                    <td>{{ Birthday }}</td>
    		                </tr>
                            <tr>
                                <td>Gender</td>
                                <td>{{ Gender }}</td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td>{{ Description }}</td>
                            </tr>
                            <tr>
                                <td>E-mail</td>
                                <td>{{ Email }}</td>
                            </tr>
    	            	</table>
            		</ul> 
                <h5>Expertise</h5>
                    <ul>
                        <table>
                                {% for ii in Expert %}
                                <div class="col-xs-2">
                                    <td class="label label-info" id="expertise_dict">{{ ii }}<td> 
                                </div>
                                {% endfor %}
                        </table>
                    </ul>
        </div>
    </section>
    {% endblock %}

page_updatestatus/templates/page_updatestatus.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/page_updatestatus.css' %}" />
<h2 class="main-title" style="font-weight:bold; font-size: 50px"> UPDATE STATUS </h2>
<hr/>
<section name="update-list" id="update-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'status:update_activity' %}">
            {% csrf_token %}
            {{ update_form }}
            <input  id="submit" type="submit" class="btn btn-secondary float-right" value="POST">
            <br>
        </form>
    </div>
</section>

{% for data in updates %}
  <section name="update-status" id="update-status">
      <div class = "status">
          <div class="row">
              <div class="col-sm-12 col-sm-offset-0">
                <div class="media" style="padding: 15px">
                  <div class="media-left">
                    <img src = " https://78.media.tumblr.com/3490e178451a95a930d793195d9b3747/tumblr_o54730zBMZ1qeu5jko2_500.gif " class="media-object" style="width: 80px;padding-right: 8px">
                  </div>
                  <div class="media-body">
                      <strong>{{user_name}}</strong>
                      <h6>Posted on {{data.date}}</h6>
                      <p>{{data.activity}}</p>
                      <div class="delete" data-id="{{data.id}}">
                        <a href="{% url 'status:clear' object_id=data.id %}"><img src="https://png.icons8.com/full-trash/androidL/1600" style="width: 35px;height 35px; top: 10px;"></a>
                      </div>
                      <div>
                        <button ng-href="javascript:void(0)" onclick="toggle_visibility('popupBoxPosition');"  class="commentBtn btn btn-primary btn-sm"> Comment </button>
                      </div>
                  </div>
                </section>
                  <section name="update-comment" id="update-comment">
                    {% for comment in data.comment_set.all %}
                      <div class = "comment">
                            <div class="row">
                              <div class="col-sm-8 col-sm-offset-0">
                                <div class="media" style="padding: 8px">
                                  <div class="media-left">
                                    <img src = " https://78.media.tumblr.com/3490e178451a95a930d793195d9b3747/tumblr_o54730zBMZ1qeu5jko2_500.gif " class="media-object" style="width: 80px;padding-right: 6px">
                                  </div>
                                  <div class="media-body">
                                    <strong>{{user_name}} says: </strong>
                                    <h6>Posted on {{comment.date}}</h6>
                                    <p>{{comment.comment}}</p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                      </div>
                    {% endfor %}
                  </section>
                    <section name="popupBoxPosition" id="popupBoxPosition">
                      <div class="popupBoxWrapper">
                        <div class="popupBoxContent">
                          <form id="form" method="POST" action="{% url 'status:update_comment' pk=data.id %}">
                            <h2>Add Comment</h2>
                            <br>
                            {% csrf_token %}
                            {{ comment_form }}
                            <br>
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post Comment">
                            <button ng-href="javascript:void(0)" onclick="toggle_visibility('popupBoxPosition');"> Cancel </button>
                          </form>
                        </div>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
{% endfor %}
<hr/>

<script type="text/javascript">
  <!--
   function toggle_visibility(id) {
    var e = document.getElementById(id);
    if(e.style.display == 'block')
     e.style.display = 'none';
    else
     e.style.display = 'block';
   }
  //-->
</script>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="TUGAS 1">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

    <title>
        {% block title %} Kelompok 9 PPW-C {% endblock %}
    </title>
</head>

<body>
 <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg" style="background-color: #e6f9ff">
          <a class="navbar-brand navbar-left" href="#" >9book</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav" background-color: "#ccf5ff">
            <ul class="navbar-nav navbar-right">
              <li class="nav-item">
                <a class="nav-link" href="/status/">Status</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/profile-page/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/add-friend/">Add Friend</a>
              </li>
			  <li class="nav-item">
			    <a class="nav-link" href="/dashboard/">Stats</a>
			  </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}

    {%block footer%}
    <p align='center' style='color:white'>Made with love and passion</p>
	<p align='center' style='color:white'>&copy; Kelompok 9 PPW-C 2017</p>
    {%endblock%}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}

</html>